#!/bin/bash

sudo apt-add-repository ppa:fish-shell/release-3
sudo apt update
sudo apt install fish
sudo apt install i3 i3lock i3block xbacklight xautolock
# background img viewer
sudo apt install feh
sudo apt install fzf jq copyq arandr python3 python3-tk
sudo apt install redshift redshift-gtk
sudo apt install fonts-font-awesome
sudo apt install rxvt-unicode
sudo apt install neovim

curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
