#! /bin/sh

sxhkd &
sh $HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config top_padding		 0
bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# border colors
bspc config normal_border_color "#6279B8"
bspc config active_border_color "#66A5E1"
bspc config focused_border_color "#AACDEE"

# programs
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a google-chrome desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
