#!/bin/bash

sudo apt-add-repository ppa:fish-shell/release-3
sudo apt-get update
sudo apt-get install fish
sudo apt-get install i3
sudo apt-get install fzf jq copyq

curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
